//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerDAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTab
    {
        public int Project_ID { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Priority { get; set; }

        public UsersTab Manager { get; set; }

        public int NoofTasks { get; set; }

        public int Completed { get; set; }
    }
}
